### ISSUE TITLE
两个问题求解

### ISSUE THREAD

**Issue by shmt86** [jerry048/Dedicated-Seedbox#1]
用3o跑完星大脚本，再跑大佬的优化脚本

1、deluge优化出现以下提示
Failed to stop deluged@shmt86.service: Unit deluged@shmt86.service not loaded.
/dev/fd/62: line 585: /home/shmt86/.config/deluge/ltconfig.conf: No such file or directory
Failed to start deluged@shmt86.service: Unit deluged@shmt86.service not found.
2、系统优化出现以下提示
Optimizing CPU
E: Failed to fetch http://ftp.de.debian.org/debian/pool/main/l/linux/libcpupower1_4.19.132-1_amd64.deb  404  Not Found [IP: 141.76.2.4 80]
E: Failed to fetch http://ftp.de.debian.org/debian/pool/main/l/linux/linux-cpupower_4.19.132-1_amd64.deb  404  Not Found [IP: 141.76.2.4 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
mkdir: cannot create directory ‘/etc/tuned/profile’: No such file or directory
touch: cannot touch '/etc/tuned/profile/tuned.conf': No such file or directory
/dev/fd/62: line 10: /etc/tuned/profile/tuned.conf: No such file or directory
/dev/fd/62: line 25: /sbin/tuned-adm: No such file or directory
Optimizing NIC Configuration
Some Configurations might not be supported by the NIC

**Comment by jerry048** [comment]
1. 你确定你跑星大脚本的时候，用的用户名字是shmt86吗，还是说deluge没有装上

2. 跑一次 `apt-get update` 试试看
