### ISSUE TITLE
qbittorrent v4.5.2 下载量统计异常

### ISSUE THREAD

**Issue by 9191521** [jerry048/Dedicated-Seedbox#11]
webui及tracker 统计的下载量大于种子大小，有时候甚至达到2倍，这个是设置的问题吗？

**Comment by jerry048** [comment]
在libtorrent設定中我采用了：
[strict_end_game_mode](https://www.libtorrent.org/reference-Settings.html#:~:text=default-,strict_end_game_mode,-bool) = false
這個設定可能會導致真實下載大過種子大小。這個設定在別的版本都是一樣的，不是4.5.2獨有。
