### ISSUE TITLE
New version qbittorrent 4.5.3

### ISSUE THREAD

**Issue by cdorabiatto** [jerry048/Dedicated-Seedbox#12]
good morning, how are you?

could you please upgrade the script to new qbittorrent version?

https://www.qbittorrent.org/download

Thank you

**Comment by cdorabiatto** [comment]
Thank you

**Comment by cdorabiatto** [comment]
Is only install again over old instalation?

**Comment by jerry048** [comment]
This would depend on what old installation you have. In general I would recommend a clean install.
