### ISSUE TITLE
bash: /dev/fd/63admin: 没有那个文件或目录

### ISSUE THREAD

**Issue by firster520** [jerry048/Dedicated-Seedbox#14]
![image](https://github.com/jerry048/Dedicated-Seedbox/assets/64927618/63de6974-1bd0-4f41-84f5-5f32ca2492c9)
这个错误提示是要可以科学上网才行么

**Comment by jerry048** [comment]
1. 注意空格
2. IP漏了
3. 請不要用弱密碼

**Comment by firster520** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
