### ISSUE TITLE
请问一开始的时候指定缓存错了，后续不重新安装的话有办法改过来吗？

### ISSUE THREAD

**Issue by LevineWoo** [jerry048/Dedicated-Seedbox#15]
如题，我尝试打开了/home/root/qbittorrent/Downloads
但里面是空的。

**Comment by jerry048** [comment]
qB設定中沒得改嗎？

**Comment by LevineWoo** [comment]
> qB設定中沒得改嗎？

抱歉。
我以为和qb中磁盘缓存的是不同的东西。那我改好了，谢谢。
