### ISSUE TITLE
请问版本怎么更新呢？还有安装完毕以后，怎么修改配置

### ISSUE THREAD

**Issue by litanwei** [jerry048/Dedicated-Seedbox#19]
开发者好，请问安装完毕以后，如何更新已经安装完的软件呢？
另外，如果修改配置，比如安装的时候缓存设置是1024，修改成2048
谢谢

**Comment by jerry048** [comment]
> 如何更新已经安装完的软件呢

脚本沒有考慮升級，直接再運行的話有概率可以，有概率會出bug。建議重裝，或者手動排查升級。
> 如果修改配置，比如安装的时候缓存设置是1024，修改成2048

視乎情況而定吧，如果是4.1.9的話要進config文件更改，如果4.2.x或以上就可以在應用設定内改
