### ISSUE TITLE
Not an issue but...

### ISSUE THREAD

**Issue by pemaaaw** [jerry048/Dedicated-Seedbox#3]
Can you please add ruTorrent + rTorrent with your tunning please? I loved your tunning, the performance is really good. 
thank you so much!

**Comment by jerry048** [comment]
I don't really use rTorrent so I don't think I will do it. Plus I don't think rTorrent is developed with speed in mind. It's probably better to just use qBittorrent/Deluge for the racing part and rTorrent for its functionality outside racing.

**Comment by pemaaaw** [comment]
@jerry048 you were right qbitt is the best for the racing part. honestly why im asking for rtorrent+rutorrent  support is because i can use autodl rss on it and i don't know how to use autodl rss in qBittorrent. i've been looking how to do that with qbitt anywhere but only radarr & sonarr the solution i found. but i didn't really like using radarr & sonarr, it can't download all from the rss. 
do you have any solution i can use?

**Comment by jerry048** [comment]
[The easiest way ](https://www.rapidseedbox.com/kb/use-rutorrents-autodl-irssi-plugin#:~:text=e%2C%205min%2C%207s-,Action%20tab,-Your%20autodl%2Dirssi)
