### ISSUE TITLE
脚本安全隐患

### ISSUE THREAD

**Issue by southcat** [jerry048/Dedicated-Seedbox#8]
脚本里面使用useradd命令 如果一开始运行时的参数设置的简单就可能被弱密码爆破出来,比如我就是admin被人家爆破下毒了,建议大佬这个地方可以改一下或是多个提示,网络上也有不少教程直接用的admin作为账号密码参数的

**Comment by jerry048** [comment]
我有想過這個問題 不過也不想生成一個新密碼要人記 （說真就是很多人都不會記住 然後掉密碼發issue）

我有空加個warning吧，不過就算是qb 也不應該設置弱密碼
