### ISSUE TITLE
qbittorrent安装时，最开始输入的<緩存大小(單位:MiB)>不生效

### ISSUE THREAD

**Issue by orbit666** [jerry048/Dedicated-Seedbox#9]
在https://raw.githubusercontent.com/jerry048/Dedicated-Seedbox/main/Install.sh里面
我们可以看到 Cache_qB= $cache
这个命令有错误。在赋值语句中，变量名和等号之间不能有空格。因此，正确的语法应该是：Cache_qB=$cache。
我fork了一份，修改后已经正常设置了。

**Comment by jerry048** [comment]
發個pull request吧
